repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version - sync with .github/workflows/ruff.yml
    rev: v0.4.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix, --show-fixes]
      # Run the formatter.
      - id: ruff-format